name: PAINN
hyperparameters:
  input_type: team
  scheduler:
    name: ReduceLROnPlateau
    mode: min
    factor: 0.32
    patience: 2
    threshold: 0
  training:
    max_epochs: 50
    early_stop_patience: 5
    batch_size: 32
    regression_target: home_team_win
    loss_fn:
      name: MSELoss
  optimizer:
    name: Adam
    base_learning_rate: 0.001
data:
  version: apricot
  splits:
    train_split: 0.8
    val_split: 0.1
    test_split: 0.1